{
 "title": "Vendas API - Monitoramento",
 "tags": [
  "vendas",
  "spring-boot",
  "api"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Status da Aplicação",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"vendas-api\"}",
     "legendFormat": "Status"
    }
   ]
  },
  {
   "title": "Vendas Criadas",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vendas_eventos_total{job=\"vendas-api\", evento=\"criada\"}",
     "legendFormat": "Vendas Criadas"
    }
   ]
  },
  {
   "title": "Vendas Canceladas",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vendas_eventos_total{job=\"vendas-api\", evento=\"cancelada\"}",
     "legendFormat": "Vendas Canceladas"
    }
   ]
  },
  {
   "title": "Requests por Segundo",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{job=\"vendas-api\"}[1m])",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  }
 ]
}